#This is our first github actions workflow

name: Build Application

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name : Setup Python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.10.7'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true
    
    - name: Load cached venv
      uses: actions/cache@v3
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os}}-${{ hashFiles(('**/poetry.lock'))}}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit!= 'true'
      run: poetry run make install
      shell: bash

